### ISSUE TITLE
Add IReadableArray to Bridge

### ISSUE THREAD

**Issue by ebragge** [CatalystCode/react-native#236]
IReadableArray

IWritableArray

IReadableMap

IWritableMap

**Comment by ebragge** [comment]
IReadableArray
IWritableArray
IReadableMap
IWritableMap

**Comment by rozele** [comment]
As discussed in stand-up, let's continue to use Json.NET for now (i.e., JObject and JArray), at least until we see a performance bottleneck in the JSON serialization stack.
