### ISSUE TITLE
Cannot run file JS bundle on PC

### ISSUE THREAD

**Issue by geof90** [CatalystCode/react-native#338]
The change introduced by https://github.com/CatalystCode/react-native/pull/329#discussion-diff-58977678 breaks when running on PC, because on PC paths are not prefixed by "file:///", but instead look something like "C:\path\to\file.bundle".

**Comment by rozele** [comment]
Ah, sorry Geof.  The UWP Image API we're using does not support loading an image from a file path.  Would it be possible for you to use "ms-appdata:///local/"?  I can make the changes to support that.

**Comment by geof90** [comment]
"ms-appdata:///local/" works great!
