### ISSUE TITLE
App crashes everytime it resumes

### ISSUE THREAD

**Issue by geof90** [CatalystCode/react-native#341]
I recorded a GIF showing the current behaviour. When an app goes into the background, and then is reentered by tapping the app icon again, it crashes. It doesn't crash if it is reentered by pressing the "back" button.

![animation2](https://cloud.githubusercontent.com/assets/8598682/14394608/e8e078d4-fd81-11e5-87ef-30903f49d1e5.gif)

The exception thrown is in this line https://github.com/CatalystCode/react-native/blob/ReactWindows/ReactWindows/ReactNative/ReactRootView.cs#L57

**Comment by rozele** [comment]
Thanks for pointing this out @geof90, it was a pretty trivial fix: https://github.com/CatalystCode/react-native/commit/352b7b63c783a318241745b4f6179ddc19102677
