### ISSUE TITLE
DevManager functionality

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/react-native#42]
This should include things like exception handling, debugging, etc.

**Comment by rozele** [comment]
This issue is very broad. It includes everything from debugging, loading JavaScript from a dev server, "hot" reloading of the JavaScript bundle, and red box exceptions.

**Comment by rozele** [comment]
RedBox is in a rough initial state #138.

**Comment by rozele** [comment]
This is too broad, live reloading is already supported, we need additional bugs for the fine-grained tasks (like Chrome debugging).  Closing as dupe of pending granular bugs.
