### ISSUE TITLE
All Modules defined in MainReactPackage

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/react-native#47]

**Comment by rozele** [comment]
This is a pretty coarse grained bug, but we're definitely making progress on it.  Current remaining views are:

ReactDrawerLayoutManager
ReactHorizontalScrollViewManager
ReactImageManager
ReactProgressBarViewManager
RecyclerViewBackedScrollViewManager
ReactToolbarManager
ReactViewPagerManager
ReactTextInlineImageViewManager
SwipeRefreshLayoutManager
ReactWebViewManager

We should create items to track each.

**Comment by rozele** [comment]
Additionally, we will need:

AppStateModule
AsyncStorageModule
CameraRollManager
ClipboardModule
DialogModule
IntentModul
LocationModule
NetworkingModule
NetInfoModule

**Comment by rozele** [comment]
Closing in preparation for finer grained work items.
